# Checkov skip list — inline comments are unreliable for CKV2 (graph-based) checks
# and inconsistent across local vs CI, so all skips are centralised here.
#
# VPC
#   CKV2_AWS_11  — VPC flow logging (unnecessary cost for a small wiki)
#   CKV2_AWS_1   — NACL subnet association (false positive — NACLs are attached)
#   CKV_AWS_130  — Public subnet auto-assign IP (intentionally public)
#   CKV_AWS_231  — NACL port 3389 from 0.0.0.0/0 (false positive — rule is a DENY)
#
# CloudFront
#   CKV_AWS_374  — Geo restriction (access location not confirmed)
#   CKV_AWS_86   — Access logging (unnecessary for small use)
#   CKV_AWS_310  — Origin failover (not a HA config)
#   CKV_AWS_305  — Default root object (Wiki.js handles routing)
#   CKV_AWS_68   — WAF (costly, same as Trivy AVD-AWS-0011)
#   CKV2_AWS_47  — WAF association (same as above)
#
# EC2
#   CKV_AWS_135  — EBS optimised (not needed for t3.micro wiki)
#   CKV_AWS_126  — Detailed monitoring (unnecessary cost)

skip-check:
  - CKV2_AWS_11
  - CKV2_AWS_1
  - CKV_AWS_130
  - CKV_AWS_231
  - CKV_AWS_374
  - CKV_AWS_86
  - CKV_AWS_310
  - CKV_AWS_305
  - CKV_AWS_68
  - CKV2_AWS_47
  - CKV_AWS_135
  - CKV_AWS_126
